### ISSUE TITLE
KeyError when SBOM library does not contain a version 

### ISSUE THREAD

**Issue by ghost** [anthonyharrison/sbom-manager#3]
Hey,

I am currently experiencing the issue that a library does not contain a version and the sbom manager is running into a KeyError

```
[15:51:00] ERROR    sbom_manager - 'version'
Traceback (most recent call last):
  File "/Users/timosur/Work/app-platform/app-sbom-collection/search.py", line 104, in <module>
    raise e
  File "/Users/timosur/Work/app-platform/app-sbom-collection/search.py", line 82, in <module>
    sbom_data = sbom_input.process_file(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timosur/Library/Caches/pypoetry/virtualenvs/app-sbom-collection-SPq90rSX-py3.12/lib/python3.12/site-packages/sbom_manager/input.py", line 37, in process_file
    sbom_data = self.sbom_process[self.sbom_type](filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timosur/Library/Caches/pypoetry/virtualenvs/app-sbom-collection-SPq90rSX-py3.12/lib/python3.12/site-packages/sbom_manager/input.py", line 149, in process_cyclonedx_json_file
    version = d["version"]
              ~^^^^^^^^^^^
KeyError: 'version'
``` 

This is the SBOM library which is causing the issue:

```javascript
{
      "type": "library",
      "bom-ref": "pkg:maven/mavenEcjBootstrapAgent/mavenEcjBootstrapAgent?package-id=775e6befe95c2f5a",
      "name": "mavenEcjBootstrapAgent",
      "licenses": [],
      "cpe": "cpe:2.3:a:mavenEcjBootstrapAgent:mavenEcjBootstrapAgent:*:*:*:*:*:*:*:*",
      "purl": "pkg:maven/mavenEcjBootstrapAgent/mavenEcjBootstrapAgent",
      "externalReferences": [
        {
          "url": "",
          "type": "build-meta",
          "hashes": [
            {
              "alg": "SHA-1",
              "content": "e67209a53266080be85e8848c01fd15af98700c7"
            }
          ]
        }
      ],
      "properties": [
        {
          "name": "syft:package:foundBy",
          "value": "java-cataloger"
        },
        {
          "name": "syft:package:language",
          "value": "java"
        },
        {
          "name": "syft:package:metadataType",
          "value": "JavaMetadata"
        },
        {
          "name": "syft:package:type",
          "value": "java-archive"
        },
        {
          "name": "syft:location:0:layerID",
          "value": "sha256:67eefc4c7fb1481960e7e7b769f382199f45cb08e0a20400c881a90f7a05f4f5"
        },
        {
          "name": "syft:location:0:path",
          "value": "/app/app.jar"
        },
        {
          "name": "syft:metadata:virtualPath",
          "value": "/app/app.jar:BOOT-INF/lib/lombok-1.18.30.jar:lombok/launch/mavenEcjBootstrapAgent.jar"
        }
      ]
    }
```

**Comment by anthonyharrison** [comment]
@timosurrwe  Thanks. I had assumed that all packages would have a version as a package without a version isn't very useful in looking for vulnerabilities etc.
